# Generated by Django 4.2.7 on 2025-05-08 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_client_options_alter_client_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='main.car', verbose_name='Автомобиль'),
        ),
    ]
