# Generated by Django 4.2.7 on 2025-05-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField()),
                ('rerity', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
